### PR TITLE
Handle AWS SDK errors and provide option to validate project credentials

### LINKED ISSUE #22: AWS SDK error handling
Currently there is no special handling of AWS SDK errors (such as permission errors or failed queries), with these currently throwing exceptions that end the running of the current file. More robust handling of these should be added.

### PR DESCRIPTION
**Pull request by timalces**
Aims to resolve #22 and #23, adding validation and protection from errors raised due to invalid credentials

**AWS SDK Error handling**
- Now rescues errors raised by the various AWS SDKs used, using them to create custom `AwsSdkError`s
- When running `weekly_reports.rb` and `daily_reports.rb` now rescues both `AzureApiError`s and these new `AwsSdkError`s (only), printing the output
- This prevents the application breaking if an AWS project has invalid credentials (which in turn can prevent subsequent project reports being generated
- As with Azure projects, the optional argument `verbose` provides further detail
- Also some minor updates to formatting of azure error print outs
- For `AzureProject`s, `update_bearer_token` is no longer called after initialisation, as otherwise various methods break if trying to initialise an `AzureProject` with invalid credentials

Screenshot from 2020-10-20 11-03-12

**Validating project credentials**
 - Adds a new option 'validate' to `manage_projects.rb`
- This will attempt some API/ SDK queries for the project. If any errors, the results are printed
- Users are asked if they want to run this validation after creating or updating a project, to help with checking projects before trying to generate their reports

Screenshot from 2020-10-19 16-44-41

Also includes some general fixes:
- Removes various unused AWS queries
- Adds more validations to `manage_projects.rb`

### CODE REVIEW

File: daily_reports.rb [hunk 1]
```diff
@@ -31,11 +31,13 @@
...
 def all_projects(date, slack, text, rerun, verbose, customer_facing)
-  ProjectFactory.new().all_projects_as_type.each do |project|
+  ProjectFactory.new().all_active_projects_as_type.each do |project|
     begin
       project.daily_report(date, slack, text, rerun, verbose, customer_facing)
-    rescue AzureApiError => e
+    rescue AzureApiError, AwsSdkError => e
+      puts "Generation of daily report for project #{project.name} stopped due to error: "
       puts e
+      puts "_" * 50
```
Comment (VoxSecundus) [inline daily_reports.rb:40]: Time for secret bash variables! Bash has it's own 'shell variables', which are bonus environment variables provided by the Bash shell. Instead of setting a hard value of `50` here, you could use the `ENV['COLUMNS']` variable to print as many underscores as there are character columns in the current terminal.

File: models/aws_project.rb [hunk 2]
```diff
@@ -85,8 +85,40 @@ def determine_region_mappings
     end
   end
 
+  def validate_credentials
+    puts "Validating AWS project credentials."
+    valid = true
+    begin
+      @explorer.get_cost_and_usage(compute_cost_query(DEFAULT_DATE))
+    rescue => error
```
Comment (VoxSecundus) [inline models/aws_project.rb:93]: Similar to previous comments, there are lots of errors that could be raised here. What if the system running the program has no internet connection? It would be reported as a problem with AWS, instead of raising a different error to say "we go network problems".

File: models/azure_project.rb [hunk 3]
```diff
@@ -80,8 +75,53 @@ def describe_resource_groups
...
+
+    uri = "https://management.azure.com/subscriptions/#{subscription_id}/providers/Microsoft.Commerce/RateCard?api-version=2016-08-31-preview&$filter=OfferDurableId eq 'MS-AZR-0003P' and Currency eq 'GBP' and Locale eq 'en-GB' and RegionInfo eq 'GB'"
+    response = HTTParty.get(
+      uri,
+      headers: { 'Authorization': "Bearer #{bearer_token}" }
+      )
+
+    if !response.success?
+      valid = false
+      puts "Unable to connect to AWS Pricing: #{response}\n\n"
```
Comment (VoxSecundus) [inline models/azure_project.rb:111]:
```suggestion
      puts "Unable to connect to Azure pricing API: #{response}\n\n"
```

**Review by VoxSecundus — CHANGES_REQUESTED** [review]

File: models/aws_project.rb (hunk 2 above)
Comment (timalces) [reply models/aws_project.rb]: Makes sense, thanks.

File: daily_reports.rb (hunk 1 above)
Comment (timalces) [reply daily_reports.rb:40]: Interesting! Though unfortunately doesn't work here (at least on my local machine) - don't think it warrants asking users to take extra steps to use it.

**Review by VoxSecundus — APPROVED** [review]
