### PR TITLE
Send slack message when an API error occurs

### LINKED ISSUE #86: Highlight report generation problems via slack message
If generating a daily report fails for a project (e.g. as seen with Azure API returning repeated 504s), would be helpful to send a message to slack highlighting the error.

### PR DESCRIPTION
**Pull request by VoxSecundus**
As title. Similar messages were not added for the `manage_projects.rb` or `record_logs.rb` scripts as they do not post anything else to Slack.

Resolves #86 when merged.

### CODE REVIEW

File: daily_reports.rb [hunk 1]
```diff
@@ -33,9 +33,14 @@ def all_projects(date, slack, text, rerun, verbose, customer_facing, short)
...
-      puts "Generation of daily report for project #{project.name} stopped due to error: "
-      puts e
-      puts "_" * 50
+      error = <<~MSG
+      Generation of daily report for project *#{project.name}* stopped due to error:
+      #{e}
+      #{"_" * 50}
+      MSG
+
+      project.send_slack_message(error)
```
Comment (timalces) [inline daily_reports.rb:42]: Sorry, should have specified - for both daily and weekly reports, these should only be sent if `slack` is set to `true`.

File: daily_reports.rb [hunk 2]
```diff
@@ -33,9 +33,14 @@ def all_projects(date, slack, text, rerun, verbose, customer_facing, short)
     begin
       project.daily_report(date, slack, text, rerun, verbose, customer_facing, short)
     rescue AzureApiError, AwsSdkError => e
-      puts "Generation of daily report for project #{project.name} stopped due to error: "
-      puts e
-      puts "_" * 50
+      error = <<~MSG
+      Generation of daily report for project *#{project.name}* stopped due to error:
+      #{e}
+      #{"_" * 50}
```
Comment (timalces) [inline daily_reports.rb:39]: These lines help with the text output (to divide projects), but would look nicer if they weren't in the slack message.

**Review by timalces — CHANGES_REQUESTED** [review]
